# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16MAweqCETF3yQ1DX5rXG20ybuXeV0tIq

## Import Libraries
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

"""## Load CIFAR 10 Dataset"""

BATCH_SIZE = 128

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

train_dataset = torchvision.datasets.CIFAR10(
    root='./data', train=True, download=True, transform=transform)

test_dataset = torchvision.datasets.CIFAR10(
    root='./data', train=False, download=True, transform=transform)

train_loader = torch.utils.data.DataLoader(
    train_dataset, batch_size=BATCH_SIZE, shuffle=True)

test_loader = torch.utils.data.DataLoader(
    test_dataset, batch_size=BATCH_SIZE, shuffle=False)

print("Dataset loaded!")

"""# Create the Prunable Neural Network"""

TEMPERATURE = 0.05

class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()

        self.weight = nn.Parameter(torch.randn(out_features, in_features) * 0.02)
        self.bias = nn.Parameter(torch.zeros(out_features))
        self.gate_scores = nn.Parameter(torch.randn(out_features, in_features) * 0.1)

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores / TEMPERATURE)
        pruned_weights = self.weight * gates
        return F.linear(x, pruned_weights, self.bias)

    def get_gates(self):
        return torch.sigmoid(self.gate_scores / TEMPERATURE)

class PrunableNet(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = PrunableLinear(32*32*3, 512)
        self.fc2 = PrunableLinear(512, 256)
        self.fc3 = PrunableLinear(256, 10)

    def forward(self, x):
        x = x.view(x.size(0), -1)

        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)

        return x

    def get_all_gates(self):
        return [
            self.fc1.get_gates(),
            self.fc2.get_gates(),
            self.fc3.get_gates()
        ]

"""## Sparsity Loss"""

def sparsity_loss(model):
    loss = 0
    total = 0

    for gates in model.get_all_gates():
        loss += gates.sum()
        total += gates.numel()

    return loss / total

def calculate_sparsity(model, threshold=1e-2):
    total = 0
    pruned = 0

    for gates in model.get_all_gates():
        total += gates.numel()
        pruned += (gates < threshold).sum().item()

    return 100 * pruned / total

"""## Model Training and Evaluation"""

def evaluate(model):
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            _, predicted = torch.max(outputs, 1)

            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    return 100 * correct / total

def train_model(lambda_sparse):
    model = PrunableNet().to(device)
    optimizer = optim.Adam(model.parameters(), lr=1e-3)

    EPOCHS = 15

    for epoch in range(EPOCHS):
        model.train()

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)

            ce_loss = F.cross_entropy(outputs, labels)
            sp_loss = sparsity_loss(model)

            loss = ce_loss + lambda_sparse * sp_loss

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        print(f"Lambda {lambda_sparse} | Epoch {epoch+1} | Loss: {loss.item():.4f}")

    acc = evaluate(model)
    sparsity = calculate_sparsity(model)

    print(f"\nLambda: {lambda_sparse}")
    print(f"Accuracy: {acc:.2f}%")
    print(f"Sparsity: {sparsity:.2f}%\n")

    return model, acc, sparsity

LAMBDA_VALUES = [0.1,0.5,1.0]

results = []
best_model = None
best_acc = 0

for lam in LAMBDA_VALUES:
    model, acc, sparsity = train_model(lam)
    results.append((lam, acc, sparsity))

    if acc > best_acc:
        best_acc = acc
        best_model = model

"""# Self-Pruning Neural Network

## 1. Overview
This project implements a self-pruning neural network where each weight is associated with a learnable gate. These gates control whether a weight is active or pruned during training.


## 2. Methodology

### Prunable Layer
Each weight has a corresponding gate:
- Gate values are obtained using a sigmoid function
- Final weight = weight × gate
- If gate ≈ 0 → weight is effectively pruned

### Sparsity Loss
The total loss function is:

Total Loss = CrossEntropyLoss + λ × SparsityLoss

Where:
- SparsityLoss = average of all gate values
- L1 regularization encourages gates to become zero


## 3.Results

| Lambda | Test Accuracy (%) | Sparsity (%) |
|--------|------------------|--------------|
| 0.1    | 54.64            | 22.33        |
| 0.5    | 55.26            | 48.34        |
| 1.0    | 55.35            | 63.28        |


## 4. Analysis

As λ increases, sparsity increases significantly, demonstrating that the model is successfully pruning unnecessary connections.

Despite higher sparsity, accuracy remains relatively stable. This indicates that many parameters in the network are redundant and can be removed without significantly affecting performance.

This validates the effectiveness of the self-pruning mechanism.


## 5. Gate Distribution

The distribution of gate values shows:
- A large number of values close to 0 (pruned weights)
- A smaller cluster of higher values (important weights)

This confirms that the network has learned to selectively retain important connections.


## 6. Conclusion

The model successfully learns to prune itself during training by:
- Using learnable gates
- Applying L1 sparsity regularization

This approach reduces model complexity while maintaining performance, making it suitable for resource-constrained environments.
"""